// <!-- okf:* --> ... <!-- /okf:* -->: generated by okf:generate, shown read-only, written back byte-exact.
import { PlateElement, type PlateElementProps } from 'platejs/react';
import { FolderTree } from 'lucide-react';

export function OkfGeneratedElement(props: PlateElementProps) {
  return (
    <PlateElement {...props} className="my-3">
      <div contentEditable={false} className="rounded-lg border border-border bg-muted/50 p-3 select-none">
        <div className="mb-1 flex items-center gap-2 text-xs font-medium text-muted-foreground">
          <FolderTree className="size-3.5" /> Generated index (read-only, written by okf:generate)
        </div>
        <pre className="overflow-x-auto font-mono text-xs whitespace-pre-wrap text-muted-foreground">{String(props.element.raw ?? '')}</pre>
      </div>
      {props.children}
    </PlateElement>
  );
}
